name: Prisme Fetch Flavors
description: Fetch flavors from API and generate matrix for builds

branding:
  icon: smartphone
  color: blue

inputs:
  project-api-key:
    description: 'The project API key to fetch flavors'
    required: true

outputs:
  flavors:
    description: 'JSON array of all flavors'

runs:
  using: node20
  main: dist/index.js