name: Hello World
description: Greet someone and record the time

inputs:
  project-api-key: # id of input
    description: The project API key to use
    required: true

outputs:
  time: # id of output
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js