name: Fetch Flavors
description: Fetch flavors from API and generate matrix for builds

inputs:
  project-api-key:
    description: 'The project API key to fetch flavors'
    required: true

outputs:
  matrix:
    description: 'Matrix configuration for GitHub Actions'
  flavors:
    description: 'JSON array of all flavors'

runs:
  using: node20
  main: dist/index.js